<?php

namespace Database\Seeders;

use App\Models\Attraction;
use Illuminate\Database\Seeder;

class AttractionSeeder extends Seeder
{
    public function run(): void
    {
        $attractions = [
            [
                'name' => 'Petronas Twin Towers',
                'slug' => 'petronas-twin-towers',
                'short_description' => 'Iconic 88-story twin towers, once the tallest buildings in the world, featuring a sky bridge and observation deck.',
                'description' => 'The PETRONAS Twin Towers are an iconic symbol of Malaysia and were the tallest buildings in the world from 1998 to 2004. Standing at 451.9 meters, these magnificent towers feature a distinctive postmodern Islamic-inspired design.',
                'location' => 'Kuala Lumpur City Centre',
                'address' => 'Kuala Lumpur City Centre, 50088 Kuala Lumpur',
                'latitude' => 3.1577,
                'longitude' => 101.7122,
                'entrance_fee' => 80.00,
                'opening_hours' => ['monday' => '10:00 AM - 6:00 PM', 'tuesday' => 'Closed', 'wednesday' => '10:00 AM - 6:00 PM', 'thursday' => '10:00 AM - 6:00 PM', 'friday' => '10:00 AM - 6:00 PM', 'saturday' => '9:00 AM - 9:00 PM', 'sunday' => '9:00 AM - 9:00 PM'],
                'contact_number' => '+603-2331 8080',
                'website' => 'https://www.petronastwintowers.com.my',
                'category' => 'museum',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Batu Caves',
                'slug' => 'batu-caves',
                'short_description' => 'Ancient limestone hill with caves and Hindu temples, featuring a 42.7m golden statue of Lord Murugan.',
                'description' => 'Batu Caves is a limestone hill featuring a series of caves and cave temples. It is one of the most popular Hindu shrines outside India, dedicated to Lord Murugan.',
                'location' => 'Gombak, Selangor',
                'address' => 'Batu Caves, 68100 Batu Caves, Selangor',
                'latitude' => 3.2379,
                'longitude' => 101.6840,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => '6:00 AM - 9:00 PM', 'tuesday' => '6:00 AM - 9:00 PM', 'wednesday' => '6:00 AM - 9:00 PM', 'thursday' => '6:00 AM - 9:00 PM', 'friday' => '6:00 AM - 9:00 PM', 'saturday' => '6:00 AM - 9:00 PM', 'sunday' => '6:00 AM - 9:00 PM'],
                'contact_number' => '+603-6189 6284',
                'website' => null,
                'category' => 'temple',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Langkawi Sky Bridge',
                'slug' => 'langkawi-sky-bridge',
                'short_description' => 'A spectacular curved cable-stayed bridge suspended 660 meters above sea level with breathtaking views.',
                'description' => 'The Langkawi Sky Bridge is a 125-meter curved pedestrian cable-stayed bridge in Langkawi. Accessible via the Langkawi Cable Car, it offers stunning panoramic views.',
                'location' => 'Gunung Mat Cincang, Langkawi',
                'address' => 'Langkawi SkyCab, 07000 Langkawi, Kedah',
                'latitude' => 6.3651,
                'longitude' => 99.6728,
                'entrance_fee' => 35.00,
                'opening_hours' => ['monday' => '9:30 AM - 6:00 PM', 'tuesday' => '9:30 AM - 6:00 PM', 'wednesday' => '9:30 AM - 6:00 PM', 'thursday' => '9:30 AM - 6:00 PM', 'friday' => '9:30 AM - 6:00 PM', 'saturday' => '9:30 AM - 6:00 PM', 'sunday' => '9:30 AM - 6:00 PM'],
                'contact_number' => '+604-959 4225',
                'website' => 'https://www.langkawiskycab.com',
                'category' => 'mountain',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Perdana Botanical Garden',
                'slug' => 'perdana-botanical-garden',
                'short_description' => 'A sprawling 91-hectare botanical garden in the heart of KL, perfect for nature walks and picnics.',
                'description' => 'Formerly known as Lake Gardens, Perdana Botanical Garden is the oldest and most popular public park in Kuala Lumpur.',
                'location' => 'Kuala Lumpur',
                'address' => 'Jalan Kebun Bunga, 55100 Kuala Lumpur',
                'latitude' => 3.1445,
                'longitude' => 101.6858,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => '7:00 AM - 8:00 PM', 'tuesday' => '7:00 AM - 8:00 PM', 'wednesday' => '7:00 AM - 8:00 PM', 'thursday' => '7:00 AM - 8:00 PM', 'friday' => '7:00 AM - 8:00 PM', 'saturday' => '7:00 AM - 8:00 PM', 'sunday' => '7:00 AM - 8:00 PM'],
                'contact_number' => '+603-2693 4321',
                'website' => null,
                'category' => 'park',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Semporna Islands',
                'slug' => 'semporna-islands',
                'short_description' => 'Gateway to world-class diving spots including Sipadan and Mabul islands with pristine marine life.',
                'description' => 'Semporna is a gateway to some of the world\'s best diving destinations including Sipadan and Mabul islands.',
                'location' => 'Semporna, Sabah',
                'address' => 'Semporna, 91308 Sabah',
                'latitude' => 4.4783,
                'longitude' => 118.6133,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => 'Open 24 hours', 'tuesday' => 'Open 24 hours', 'wednesday' => 'Open 24 hours', 'thursday' => 'Open 24 hours', 'friday' => 'Open 24 hours', 'saturday' => 'Open 24 hours', 'sunday' => 'Open 24 hours'],
                'contact_number' => null,
                'website' => null,
                'category' => 'island',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Kek Lok Si Temple',
                'slug' => 'kek-lok-si-temple',
                'short_description' => 'The largest Buddhist temple in Malaysia, featuring a 36.5m bronze statue of Kuan Yin.',
                'description' => 'Kek Lok Si Temple is a Buddhist temple situated in Air Itam, Penang. It is the largest Buddhist temple in Malaysia.',
                'location' => 'Air Itam, Penang',
                'address' => 'Kek Lok Si Temple, 06000 Ayer Itam, Penang',
                'latitude' => 5.4007,
                'longitude' => 100.2737,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => '8:30 AM - 5:30 PM', 'tuesday' => '8:30 AM - 5:30 PM', 'wednesday' => '8:30 AM - 5:30 PM', 'thursday' => '8:30 AM - 5:30 PM', 'friday' => '8:30 AM - 5:30 PM', 'saturday' => '8:30 AM - 5:30 PM', 'sunday' => '8:30 AM - 5:30 PM'],
                'contact_number' => '+604-828 3317',
                'website' => null,
                'category' => 'temple',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Cameron Highlands Tea Plantations',
                'slug' => 'cameron-highlands-tea-plantations',
                'short_description' => 'Rolling hills of emerald green tea plantations with stunning views and fresh mountain air.',
                'description' => 'The Cameron Highlands tea plantations offer breathtaking views of endless green hills.',
                'location' => 'Cameron Highlands, Pahang',
                'address' => 'Boh Tea Plantation, 39000 Brinchang, Pahang',
                'latitude' => 4.4957,
                'longitude' => 101.3873,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => '8:30 AM - 4:30 PM', 'tuesday' => '8:30 AM - 4:30 PM', 'wednesday' => '8:30 AM - 4:30 PM', 'thursday' => '8:30 AM - 4:30 PM', 'friday' => '8:30 AM - 4:30 PM', 'saturday' => '8:30 AM - 4:30 PM', 'sunday' => '8:30 AM - 4:30 PM'],
                'contact_number' => '+605-496 2096',
                'website' => 'https://www.boh.com.my',
                'category' => 'mountain',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Teluk Cempedak Beach',
                'slug' => 'teluk-cempedak-beach',
                'short_description' => 'A beautiful sandy beach with casuarina trees and crystal-clear waters, perfect for swimming.',
                'description' => 'Teluk Cempedak is a stunning beach in Kuantan, Pahang, known for its white sandy shores and clear waters.',
                'location' => 'Kuantan, Pahang',
                'address' => 'Teluk Cempedak, 25050 Kuantan, Pahang',
                'latitude' => 3.8194,
                'longitude' => 103.3782,
                'entrance_fee' => 0.00,
                'opening_hours' => ['monday' => 'Open 24 hours', 'tuesday' => 'Open 24 hours', 'wednesday' => 'Open 24 hours', 'thursday' => 'Open 24 hours', 'friday' => 'Open 24 hours', 'saturday' => 'Open 24 hours', 'sunday' => 'Open 24 hours'],
                'contact_number' => null,
                'website' => null,
                'category' => 'beach',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Gua Tempurung',
                'slug' => 'gua-tempurung',
                'short_description' => 'One of the largest limestone caves in Peninsular Malaysia with stunning stalactites and stalagmites.',
                'description' => 'Gua Tempurung is one of the largest limestone caves in Peninsular Malaysia, stretching over 3 kilometers.',
                'location' => 'Gopeng, Perak',
                'address' => 'Gua Tempurung, 31600 Gopeng, Perak',
                'latitude' => 4.4155,
                'longitude' => 101.1790,
                'entrance_fee' => 20.00,
                'opening_hours' => ['monday' => '9:00 AM - 4:00 PM', 'tuesday' => '9:00 AM - 4:00 PM', 'wednesday' => '9:00 AM - 4:00 PM', 'thursday' => '9:00 AM - 4:00 PM', 'friday' => '9:00 AM - 4:00 PM', 'saturday' => '9:00 AM - 5:00 PM', 'sunday' => '9:00 AM - 5:00 PM'],
                'contact_number' => '+605-359 2034',
                'website' => null,
                'category' => 'cave',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Sekayu Waterfall',
                'slug' => 'sekayu-waterfall',
                'short_description' => 'A picturesque five-tier waterfall nestled in a tropical rainforest, ideal for swimming and picnics.',
                'description' => 'Sekayu Waterfall is a beautiful five-tier waterfall located in the Sekayu Recreational Forest.',
                'location' => 'Kuala Berang, Terengganu',
                'address' => 'Hutan Lipur Sekayu, 21700 Kuala Berang, Terengganu',
                'latitude' => 5.0833,
                'longitude' => 103.0167,
                'entrance_fee' => 5.00,
                'opening_hours' => ['monday' => '8:00 AM - 6:00 PM', 'tuesday' => '8:00 AM - 6:00 PM', 'wednesday' => '8:00 AM - 6:00 PM', 'thursday' => '8:00 AM - 6:00 PM', 'friday' => '8:00 AM - 6:00 PM', 'saturday' => '8:00 AM - 7:00 PM', 'sunday' => '8:00 AM - 7:00 PM'],
                'contact_number' => '+609-624 1177',
                'website' => null,
                'category' => 'waterfall',
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($attractions as $attraction) {
            Attraction::create($attraction);
        }

        $this->command->info('Created ' . count($attractions) . ' attractions.');
    }
}
